file:"C:\\ProgramData/Git/config"	core.symlinks=false
file:"C:\\ProgramData/Git/config"	core.autocrlf=true
file:"C:\\ProgramData/Git/config"	core.fscache=true
file:"C:\\ProgramData/Git/config"	color.diff=auto
file:"C:\\ProgramData/Git/config"	color.status=auto
file:"C:\\ProgramData/Git/config"	color.branch=auto
file:"C:\\ProgramData/Git/config"	color.interactive=true
file:"C:\\ProgramData/Git/config"	help.format=html
file:"C:\\ProgramData/Git/config"	diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"	rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig	add.interactive.usebuiltin=true
file:C:/Users/4e7 Administrator/.gitconfig	user.name=0pfox
file:C:/Users/4e7 Administrator/.gitconfig	user.email=4lbr3ch7@gmail.com
file:C:/Users/4e7 Administrator/.gitconfig	filter.lfs.required=true
file:C:/Users/4e7 Administrator/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/4e7 Administrator/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/4e7 Administrator/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/4e7 Administrator/.gitconfig	core.editor="C:\Users\4e7 Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
file:C:/Users/4e7 Administrator/.gitconfig	pass.word=3picC0de
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	submodule.active=.
file:.git/config	remote.origin.url=https://github.com/0pFox/4e7-media.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.master.remote=origin
file:.git/config	branch.master.merge=refs/heads/master
